import React from "react";
import { CgWorkAlt } from "react-icons/cg";
import { type TProject } from "./types";

export const links = [
  {
    name: "Home",
    hash: "#home",
  },
  {
    name: "About",
    hash: "#about",
  },
  {
    name: "Projects",
    hash: "#projects",
  },
  {
    name: "Skills",
    hash: "#skills",
  },
  {
    name: "Experience",
    hash: "#experience",
  },
  {
    name: "Contact",
    hash: "#contact",
  },
] as const;

export const experiencesData = [
  {
    title: "Senior Front-End Developer",
    location: "Gigster, Remote",
    description: "Worked on various web3 projects.",
    icon: React.createElement(CgWorkAlt),
    date: "2021 - 2022",
  },
  {
    title: "Senior Front-End Developer",
    location: "Forj Network, Remote",
    description:
      "Built an NFT white-label platform, as well as an admin panel to customize NFT properties, collections, etc..",
    icon: React.createElement(CgWorkAlt),
    date: "2022 - 2023",
  },
  {
    title: "Senior Front-End Developer",
    location: "Freeway, Remote",
    description: "Building Freeway Staking/Rewards platform",
    icon: React.createElement(CgWorkAlt),
    date: "2022 - present",
  },
] as const;

export const skillsData = [
  "HTML",
  "CSS",
  "JavaScript",
  "TypeScript",
  "React",
  "Next.js",
  "Node.js",
  "Angular",
  "Git",
  "Tailwind",
  "Prisma",
  "MongoDB",
  "Redux",
  "GraphQL",
  "Apollo",
  "PostgreSQL",
  "Framer Motion",
] as const;

export const projects: TProject[] = [
  {
    id: 28,
    name: "Freeway",
    description: "DeFi Staking App",
    image_path: "/images/freeway.png",
    deployed_url: "https://fwcs-freeway2-app.freeway.io/login/",
    github_url: "",
    category: ["react", "blockchain"],
    key_techs: ["NextJS", "Typescript", "TailwindsCSS"],
  },
  {
    id: 27,
    name: "VolfiSwap",
    description: "ERC20 token exchange platform.",
    image_path: "/images/uniswap.png",
    deployed_url: "https://volswap-nstanogias.vercel.app/",
    github_url: "https://github.com/nstanogias/uniswap-web3-clone",
    category: ["react", "blockchain"],
    key_techs: ["NextJS", "Typescript", "TailwindsCSS"],
  },
  {
    id: 0,
    name: "Crypto OrderBook",
    description:
      "Display a realtime orderbook. User is able to switch between bitcoin/usd and eth/usd market data by clicking on a button",
    image_path: "/images/orderbook.png",
    deployed_url: "https://my-orderbook.vercel.app/",
    github_url: "https://github.com/nstanogias/my-orderbook",
    category: ["react"],
    key_techs: ["React", "Styled Components", "Websocket API", "Webworker"],
  },
  {
    id: 16,
    name: "YouTv",
    description: "Online streaming service",
    image_path: "/images/youtv.png",
    deployed_url: "https://youtv.dk/",
    category: ["react"],
    key_techs: [
      "React",
      "NextJS",
      "Typescript",
      "Styled Components",
      "Redux",
      "Graphql",
    ],
  },
  {
    id: 17,
    name: "Nora",
    description: "Digital investment platform",
    image_path: "/images/nora.png",
    deployed_url: "https://investor.nordea.dk/sg/investment-guide/#/",
    category: ["angular"],
    key_techs: ["Angular", "Java", "Spring Boot", "Typescript"],
  },
  {
    id: 18,
    name: "NextPlat",
    description: "NFT Marketplace",
    image_path: "/images/nextplat.png",
    deployed_url: "https://nextplat-nft-drop.vercel.app/",
    category: ["react", "blockchain"],
    key_techs: ["React", "NextJS", "Typescript", "TailwindCSS", "Strapi CMS"],
  },
  {
    id: 19,
    name: "Raiffaisen",
    description: "Digital services platform",
    image_path: "/images/raiffaisen.png",
    deployed_url:
      "https://www.rbinternational.com/de/kunden/online-services.html#ihrstart",
    category: ["angular"],
    key_techs: ["Angular", "Java", "Spring Boot", "Typescript"],
  },
  {
    id: 20,
    name: "IOT sensors",
    description: "Internet of things sensor data",
    image_path: "/images/iot-sensors.png",
    deployed_url: "",
    github_url: "https://github.com/nstanogias/sensors-worker",
    category: ["react"],
    key_techs: [
      "React",
      "Typescript",
      "TailwindsCSS",
      "Websocket API",
      "Webworker",
    ],
  },
  {
    id: 21,
    name: "Pokedex",
    description: "Pokedex clone with NextJs",
    image_path: "/images/pokedex.png",
    deployed_url: "https://next-pokedex-six.vercel.app/",
    github_url: "https://github.com/nstanogias/next-pokedex",
    category: ["react"],
    key_techs: ["NextJS", "Typescript", "TailwindsCSS", "SWR API"],
  },
  {
    id: 22,
    name: "Cryptos-list",
    description: "Displaying a grid of most popular cryptos",
    image_path: "/images/currencies-list.png",
    deployed_url: "https://cryptos-list.vercel.app/",
    github_url: "https://github.com/nstanogias/cryptos-list",
    category: ["react", "blockchain"],
    key_techs: ["React", "Typescript", "TailwindsCSS"],
  },
  {
    id: 23,
    name: "DAI transfer events board",
    description: "Board with latest dai smart contract transfer events",
    image_path: "/images/dai_transactions-history.png",
    deployed_url: "",
    github_url: "https://github.com/nstanogias/dai-transfer-events-board",
    category: ["react", "blockchain"],
    key_techs: ["React", "Typescript", "TailwindsCSS"],
  },
  {
    id: 24,
    name: "NFT Admin board",
    description: "NFT admin panel",
    image_path: "/images/nft-adminpanel.png",
    deployed_url: "",
    github_url: "",
    category: ["react", "blockchain"],
    key_techs: ["NextJS", "Typescript", "TailwindsCSS"],
  },
  {
    id: 25,
    name: "Currency Exchanger",
    description: "Angular currency exchanger using fixer API",
    image_path: "/images/currency-exchanger.png",
    deployed_url: "",
    github_url: "https://github.com/nstanogias/currency-exchanger",
    category: ["angular"],
    key_techs: ["Angular", "Typescript"],
  },
  {
    id: 26,
    name: "Web3 crowdfunding",
    description: "Web3 crowdfunding using thirdweb sdk custom smart contract",
    image_path: "/images/web3-crowdfunding.png",
    deployed_url: "https://web3-crowdfunding-nstanogias.vercel.app/",
    github_url: "https://github.com/nstanogias/web3_crowdfunding",
    category: ["react", "blockchain"],
    key_techs: ["NextJS", "Typescript", "TailwindsCSS"],
  },
  {
    id: 9,
    name: "Coinbase",
    description:
      "coinbase dashboard where users can exchange tokens. Tech: Next.js, sanity CMS, thirdweb SDK, styled components",
    image_path: "/images/coinbase_blockchain.png",
    deployed_url: "https://coinbase-blockchain-seven.vercel.app/",
    github_url: "https://github.com/nstanogias/coinbase-blockchain",
    category: ["blockchain"],
    key_techs: ["React", "NextJS", "Typescript", "Styled Components"],
  },
  {
    id: 10,
    name: "Coinmarketcap",
    description:
      "coinmarketcap clone using moralis as a web3 development framework. token exchange functionality and chat functionality using gun.js lib",
    image_path: "/images/coinmarketcap_blockchain.png",
    deployed_url: "https://coinmarketcap-moralis.vercel.app/",
    github_url: "https://github.com/nstanogias/coinmarketcap-moralis",
    category: ["blockchain"],
    key_techs: ["React", "NextJS", "Coinmarketcap API", "TailwindCSS"],
  },
  {
    id: 11,
    name: "Erc20-staking",
    description: "",
    image_path: "/images/erc20-staking.png",
    deployed_url: "https://erc20-staking-dapp.vercel.app/",
    github_url: "https://github.com/nstanogias/erc20-staking-dapp",
    category: ["blockchain"],
    key_techs: [
      "React",
      "NextJS",
      "Thirdweb",
      "Solidity",
      "Typescript",
      "TailwindCSS",
    ],
  },
  // {
  //   id: 12,
  //   name: "Imdb",
  //   description: "Imdb clone",
  //   image_path: "/images/imdb_clone.png",
  //   deployed_url: "https://imdb-nextjs-roan.vercel.app/",
  //   github_url: "https://github.com/nstanogias/imdb-nextjs",
  //   category: ["react"],
  //   key_techs: ["React", "NextJS", "TailwindCSS"],
  // },
  {
    id: 13,
    name: "Movies",
    description: "",
    image_path: "/images/next_movies.png",
    deployed_url: "https://movies-nextjs-strapi.vercel.app/",
    github_url: "https://github.com/nstanogias/movies-nextjs-frontend",
    category: ["react"],
    key_techs: ["React", "NextJS", "TailwindCSS"],
  },
  {
    id: 14,
    name: "NFT Marketplace",
    description:
      "nft marketplace with nextjs, tailwindCSS, thirdweb sdk, sanity",
    image_path: "/images/nft-marketplace.png",
    deployed_url: "https://nft-marketplace-ruddy.vercel.app/",
    github_url: "https://github.com/nstanogias/nft-marketplace",
    category: ["blockchain"],
    key_techs: ["React", "NextJS", "Thirdweb", "Typescript", "TailwindCSS"],
  },
  {
    id: 15,
    name: "Spotify Clone",
    description:
      "spotify clone with nextjs, nextauth, recoil state management and spotify api",
    image_path: "/images/spotify_clone.png",
    deployed_url: "https://spotify-clone-nstanogias.vercel.app/",
    github_url: "https://github.com/nstanogias/spotify-clone",
    category: ["react"],
    key_techs: ["React", "NextJS", "Nextauth", "Typescript", "TailwindCSS"],
  },
  {
    id: 8,
    name: "Amazon",
    description:
      "amazon blockchain where you can buy digital assets with amazon crypto coins",
    image_path: "/images/amazon_blockchain.png",
    deployed_url: "https://amazon-moralis-blockchain.vercel.app/",
    github_url: "https://github.com/nstanogias/amazon-moralis-blockchain",
    category: ["blockchain"],
    key_techs: ["React", "NextJS", "Moralis", "Typescript", "TailwindCSS"],
  },
  // {
  //   id: 1,
  //   name: "Expensify",
  //   description: "MERN app to track your expenses",
  //   image_path: "/images/expensify.png",
  //   deployed_url: "https://mern-expensify.herokuapp.com/",
  //   github_url: "https://github.com/nstanogias/react-expensify",
  //   category: ["node", "mongo", "react"],
  //   key_techs: ["React", "Context API", "Node", "Express", "Mongo", "REST API"],
  // },

  // {
  //   id: 2,
  //   name: "Tournament portal",
  //   description: "CRUD app displaying tournament cards",
  //   image_path: "/images/tourPortal.png",
  //   deployed_url: "https://tournament-portal.herokuapp.com/",
  //   github_url: "https://github.com/nstanogias/react-tournament-portal",
  //   category: ["react"],
  //   key_techs: ["React", "Redux", "Styled Components"],
  // },

  // {
  //   id: 3,
  //   name: "Date App",
  //   description: "Fullstack app build with Angular and Spring Boot",
  //   image_path: "/images/dateapp.png",
  //   deployed_url: "https://angular-dateapp.herokuapp.com/",
  //   github_url: "https://github.com/nstanogias/dateapp-frontend",
  //   category: ["angular", "spring"],
  //   key_techs: ["Angular", "Spring Boot"],
  // },
  // {
  //   id: 4,
  //   name: "Task App",
  //   description: "CRUD app with angular",
  //   image_path: "/images/taskCrud.png",
  //   deployed_url: "https://my-angular-task-project.herokuapp.com/",
  //   github_url: "https://github.com/nstanogias/angular-task-frontend",
  //   category: ["angular", "spring"],
  //   key_techs: ["Angular", "Spring Boot"],
  // },
  // {
  //   id: 5,
  //   name: "Massage Salon",
  //   description: "Small react app using styled components",
  //   image_path: "/images/massage.png",
  //   deployed_url: "#",
  //   github_url: "https://github.com/nstanogias/react-massage-salon",
  //   category: ["react"],
  //   key_techs: ["React", "Styled Components"],
  // },
  // {
  //   id: 6,
  //   name: "Ski Store",
  //   description: "Ecommerce app built with Angular and Spring Boot",
  //   image_path: "/images/skistore.png",
  //   deployed_url: "#",
  //   github_url: "https://github.com/nstanogias/ski-store-client",
  //   category: ["angular", "spring"],
  //   key_techs: ["Angular", "Spring Boot"],
  // },
  // {
  //   id: 7,
  //   name: "Realand",
  //   description: "Real Estate Forum",
  //   image_path: "/images/realand.png",
  //   deployed_url: "https://realand-nstanogias.vercel.app/",
  //   github_url: "https://github.com/nstanogias/realand",
  //   category: ["react"],
  //   key_techs: ["React", "NextJS"],
  // },
];
